In [2]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [4]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.4501, 0.8188, 0.0466, 0.1952],
        [0.4696, 0.3780, 0.8732, 0.7370],
        [0.1883, 0.0132, 0.8550, 0.3626]])
tensor([[ 1.1097, -1.5028,  0.6076, -2.8188],
        [-1.7598,  3.6763,  0.5378, -0.2668],
        [-1.0711, -1.1776, -0.1402,  0.2604]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [6]:
import torch
a = torch.tensor(
[[10, 10, 10, 10 ,10],
[10, 10, 10, 10, 10],
[10, 10, 10, 10, 10],
[10, 10, 10, 10, 10],
[10, 10, 10, 10, 10],
],
dtype=torch.int32
)
print(a)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]], dtype=torch.int32)


In [8]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)


Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


In [15]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])
print(a[1].shape)
print(a[1:, 2:4].shape)
ket_qua = a[:, :, -2:]
print(ket_qua.shape)

Original tensor:
tensor([[[ 0.6811,  0.2197, -0.8881, -0.4396, -0.6824],
         [ 1.2168, -0.0145,  0.3876,  1.7065, -0.3746],
         [-0.7642, -0.7101, -0.5790, -0.3762,  0.2226],
         [-0.2048, -1.8867, -0.6187,  0.0723, -0.0488]],

        [[ 0.9325, -1.7236, -0.1071, -1.2168, -1.7918],
         [-2.8848,  0.0546, -0.9382, -0.4921,  0.7686],
         [ 1.5380,  1.0519, -0.7715, -0.8980,  1.1678],
         [ 1.0561,  0.0936,  0.0320, -0.1388, -0.4681]],

        [[-0.7841,  1.1830, -1.0722,  1.2969, -0.9356],
         [ 0.4525,  1.6035, -0.2971,  0.7826, -0.5073],
         [-1.3190, -0.9311, -2.3667,  0.2557, -0.2313],
         [ 0.2100, -0.6573, -0.5109,  0.2338, -0.4045]]])

Tensor a[1]:
tensor([[ 0.9325, -1.7236, -0.1071, -1.2168, -1.7918],
        [-2.8848,  0.0546, -0.9382, -0.4921,  0.7686],
        [ 1.5380,  1.0519, -0.7715, -0.8980,  1.1678],
        [ 1.0561,  0.0936,  0.0320, -0.1388, -0.4681]])

Tensor a[1:, 2:4]:
tensor([[[ 1.5380,  1.0519, -0.7715, -0.8980,  1.1

In [18]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

a_2x6 = a.reshape(2, 6)
print("\nReshape to 2 x 6:")
print(a_2x6)
print("Shape mới:", a_2x6.shape)

Original:
tensor([[ 0.8503,  0.7815, -0.2625, -0.3482],
        [-0.8317,  0.7252,  0.4698,  0.7690],
        [-0.4901,  2.1034, -0.7277, -1.7824]])

Flatten:
tensor([ 0.8503,  0.7815, -0.2625, -0.3482, -0.8317,  0.7252,  0.4698,  0.7690,
        -0.4901,  2.1034, -0.7277, -1.7824])

Reshape to 3 x 2 x 2:
tensor([[[ 0.8503,  0.7815],
         [-0.2625, -0.3482]],

        [[-0.8317,  0.7252],
         [ 0.4698,  0.7690]],

        [[-0.4901,  2.1034],
         [-0.7277, -1.7824]]])

Reshape to 2 x 6:
tensor([[ 0.8503,  0.7815, -0.2625, -0.3482, -0.8317,  0.7252],
        [ 0.4698,  0.7690, -0.4901,  2.1034, -0.7277, -1.7824]])
Shape mới: torch.Size([2, 6])


In [20]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

print("\nMean 1:")
print(torch.mean(a, dim=1))
print("\nStandard deviation 1:")
print(torch.std(a, dim=1))
print("\nCumulative sum 1:")
print(torch.cumsum(a, dim=1))

tensor([[ 0.2701,  0.8629, -1.0707, -0.0975],
        [ 0.6397,  0.2462, -1.2034,  0.0513],
        [-1.3831,  1.5235,  1.3878,  0.3872]])

Mean:
tensor([-0.1578,  0.8775, -0.2954,  0.1136])

Standard deviation:
tensor([1.0771, 0.6388, 1.4592, 0.2483])

Cumulative sum:
tensor([[ 0.2701,  0.8629, -1.0707, -0.0975],
        [ 0.9098,  1.1091, -2.2741, -0.0462],
        [-0.4733,  2.6325, -0.8863,  0.3409]])

Mean 1:
tensor([-0.0088, -0.0665,  0.4788])

Standard deviation 1:
tensor([0.8110, 0.7964, 1.3407])

Cumulative sum 1:
tensor([[ 0.2701,  1.1330,  0.0623, -0.0352],
        [ 0.6397,  0.8859, -0.3174, -0.2662],
        [-1.3831,  0.1404,  1.5282,  1.9153]])


In [22]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = 3 * x**2 + 2 * x + 1
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


In [27]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 1.4932],
        [ 0.5357],
        [-0.1191]], requires_grad=True)
Learned coefficients:
tensor([[1.0000],
        [1.9999],
        [2.9993]], requires_grad=True)


In [29]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)


A = tensor(4.5383, requires_grad=True)
B = tensor(4.4616, requires_grad=True)
C = tensor(3.4616, requires_grad=True)
D = tensor(2.4616, requires_grad=True)


In [34]:
# Bài 11
import torch
X = torch.arange(24, dtype=torch.float32)
print("Tensor X ban đầu:", X.shape)

X_4_6 = X.reshape(4, 6)
X_2_12 = X.reshape(2, 12)
X_2_3_4 = X.reshape(2, 3, 4)

print("Shape 4 x 6:", X_4_6.shape)
print("Shape 2 x 12:", X_2_12.shape)
print("Shape 2 x 3 x 4:", X_2_3_4.shape)

Tensor X ban đầu: torch.Size([24])
Shape 4 x 6: torch.Size([4, 6])
Shape 2 x 12: torch.Size([2, 12])
Shape 2 x 3 x 4: torch.Size([2, 3, 4])


In [38]:
A = torch.randn(3, 4)
B = torch.randn(3, 4) + 1.0

print("\nPhép tính A và B")
print("A + B:\n", A + B)
print("A * B (nhân từng phần tử):\n", A * B)
print("A / B (chia từng phần tử):\n", A / B)

print("\nTrung bình theo cột của A (dim=0):", torch.mean(A, dim=0))
print("Độ lệch chuẩn theo cột của A (dim=0):", torch.std(A, dim=0))


Phép tính A và B
A + B:
 tensor([[ 3.3710,  1.8878,  2.3248,  3.3592],
        [-0.4026,  1.8057, -0.6054,  1.1754],
        [ 1.1925, -0.4210,  2.8464,  1.8688]])
A * B (nhân từng phần tử):
 tensor([[ 2.5236,  0.3910,  1.3485,  2.7446],
        [-0.8834, -1.7374, -2.5402, -1.7238],
        [ 0.1171, -1.8364,  2.0256, -1.5632]])
A / B (chia từng phần tử):
 tensor([[ 2.0038,  0.1434,  1.0931,  0.7174],
        [-0.6537, -0.2779, -1.4588, -0.4199],
        [ 0.0996, -1.3626,  1.0023, -0.2511]])

Trung bình theo cột của A (dim=0): tensor([ 1.0389, -0.6800,  0.2380, -0.0247])
Độ lệch chuẩn theo cột của A (dim=0): tensor([1.0973, 0.9094, 1.8762, 1.2417])


In [37]:
x = torch.tensor(2.0, requires_grad=True)
y = 2 * (x**2) + 5 * x + 3

y.backward()

print("\nKiểm tra đạo hàm:")
print("Đạo hàm bằng PyTorch (x.grad):", x.grad.item())
print("Đạo hàm thủ công: 13")


Kiểm tra đạo hàm:
Đạo hàm bằng PyTorch (x.grad): 13.0
Đạo hàm thủ công: 13


In [36]:
import numpy as np

polynomial = np.poly1d([2, -3, 5])
N = 50
X_np = np.random.randn(N, 1) * 3
Y_np = polynomial(X_np)

XX = np.hstack([X_np * X_np, X_np, np.ones_like(X_np)])

w = torch.randn(3, 1, requires_grad=True)
x_tensor = torch.tensor(XX, dtype=torch.float32)
y_tensor = torch.tensor(Y_np, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(2000):
    optimizer.zero_grad()
    y_pred = x_tensor @ w
    mse = torch.mean(torch.square(y_tensor - y_pred))
    mse.backward()
    optimizer.step()

print("\nKết quả huấn luyện đa thức:")
print("Các hệ số học được [w2, w1, w0]:")
print(w.detach().numpy().flatten())


Kết quả huấn luyện đa thức:
Các hệ số học được [w2, w1, w0]:
[ 2.0317214 -3.0075657  4.1101084]
